name: super_editor
description: Configurable, composable, extensible text editor and document renderer for Flutter.
version: 0.3.0-dev.43
homepage: https://github.com/superlistapp/super_editor
funding:
  - https://flutterbountyhunters.com
  - https://github.com/sponsors/matthew-carroll
topics:
  - rich-text-editor
  - editor
  - quill
  - markdown

screenshots:
  - description: "SuperEditor on Mac desktop"
    path: doc/marketing/screenshot_mac_desktop.png
  - description: "SuperEditor dark mode"
    path: doc/marketing/screenshot_mac_desktop_dark-mode.png
  - description: "SuperEditor text selection"
    path: doc/marketing/screenshot_mac_desktop_text-selection.png
  - description: "SuperEditor text styles"
    path: doc/marketing/screenshot_mac_desktop_bold-selection.png

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  attributed_text: ^0.4.5
  characters: ^1.3.0
  collection: ^1.15.0
  dart_quill_delta: ^9.4.1
  follow_the_leader: ^0.5.2
  http: ^1.2.2
  linkify: ^5.0.0
  logging: ^1.3.0
  markdown: ^7.2.1
  super_text_layout: ^0.1.18
  super_keyboard: ^0.3.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  overlord: ^0.4.2

  # Dependencies for testing tools that we ship with super_editor
  flutter_test:
    sdk: flutter
  flutter_test_robots: ^0.0.24
  clock: ^1.1.1
  golden_toolkit: ^0.15.0
  meta: ^1.8.0
  matcher: ^0.12.16+1
  mockito: ^5.0.4
  path: ^1.8.3
  text_table: ^4.0.3

#dependency_overrides:
#  # Override to local mono-repo path so devs can test this repo
#  # against changes that they're making to other mono-repo packages
#  attributed_text:
#    path: ../attributed_text
#  super_text_layout:
#    path: ../super_text_layout

dev_dependencies:
  args: ^2.3.1
  flutter_lints: ^2.0.1
  flutter_test_runners: ^0.0.4
  flutter_test_goldens: ^0.0.7
  golden_bricks: ^1.0.0
  golden_runner: ^0.2.0

flutter:
  # no Flutter configuration
