name: super_editor_clipboard
description: "Rich text copy/paste extensions on super_editor."
version: 0.2.4
repository: https://github.com/superlistapp/super_editor/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_test_runners: ^0.0.4
  html2md: ^1.3.2
  logging: ^1.3.0
  super_clipboard: ^0.9.1
  super_editor: ^0.3.0-dev.48
  super_keyboard: ^0.3.1

#dependency_overrides:
#  super_editor:
#    path: ../super_editor
#  super_editor_markdown:
#    path: ../super_editor_markdown
#  super_keyboard:
#    path: ../super_keyboard

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  super_text_layout: ^0.1.19

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SuperEditorClipboardPlugin
